databases:
  - name: postgres
    ipAllowList: []
    databaseName: budget_app_production
    user: budget_app_production
    plan: free

services:
  - type: web
    name: mana
    env: ruby
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false