databases:
  - name: postgres
    ipAllowList: []
    databaseName: mana
    user: budget_app
    password: budGET

services:
  - type: web
    name: mana
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false